image: debian:stable

include:
  - template: Code-Quality.gitlab-ci.yml

before_script:
  - echo "Updating package index" && echo deb http://ftp.de.debian.org/debian buster main > /etc/apt/sources.list.d/buster-main.list
  - echo "Updating packages" && apt-get update -qy
  - echo "Installing curl command" && apt-get install curl -y
  - echo "Installing OpenJDK11 JRE" && apt-get install default-jdk -y
  - echo "Installing Maven" && apt install maven -y
  - echo "Installing nodejs and npm" && apt install nodejs npm -y
  - echo "Installing heroku" && curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn clean install -Dmaven.test.skip=true

test-job:
  stage: test
  script:
    - echo "Running tests on $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn test

deploy-server-job:
  stage: deploy
  script:
    - echo "Deploying server from $CI_COMMIT_BRANCH branch to heroku minihearthstone-server"

deploy-client-job:
  stage: deploy
  script:
    - echo "Deploying client from $CI_COMMIT_BRANCH branch to heroku minihearthstone-server"

code_quality:
  variables:
    REPORT_FORMAT: html
  stage: build
  script:
    - echo "Running code quality on $CI_COMMIT_BRANCH branch"
  artifacts:
    expose_as: "Code Quality Report"
    paths: [gl-code-quality-report.html]

metrics:
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
