include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build-job:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn install

test-job:
  image: maven:3-jdk-8
  stage: test
  script:
    - echo "Running tests on $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn test

deploy-server-job:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: manual
  script:
    - echo "Deploying server from $CI_COMMIT_BRANCH branch to heroku $HEROKU_APP_SERVER"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd /builds/rkmarechal/minihearthstone/code/server
    - dpl --provider=heroku --app=$HEROKU_APP_SERVER --api-key=$HEROKU_API_KEY
  only:
    - master

deploy-client-job:
  stage: deploy
  image: ruby:latest
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - when: manual
  script:
    - echo "Deploying client from $CI_COMMIT_BRANCH branch to heroku $HEROKU_APP_CLIENT"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd /builds/rkmarechal/minihearthstone/code/client
    - dpl --provider=heroku --app=$HEROKU_APP_CLIENT --api-key=$HEROKU_API_KEY
  only:
    - master

code_quality:
  variables:
    REPORT_FORMAT: html
  stage: build
  script:
    - echo "Running code quality on $CI_COMMIT_BRANCH branch"
  artifacts:
    expose_as: "Code Quality Report"
    paths: [gl-code-quality-report.html]

metrics:
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt

