image: maven:3-jdk-8

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  # - execute

build-job:
  stage: build
  script:
    - echo "Building $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn clean install -Dmaven.test.skip=true

test-job:
  stage: test
  script:
    - echo "Running tests on $CI_COMMIT_BRANCH branch"
    - cd /builds/rkmarechal/minihearthstone/code/server
    - mvn test

code_quality:
  variables:
    REPORT_FORMAT: html
  stage: build
  script:
    - echo "Running code quality on $CI_COMMIT_BRANCH branch"
  artifacts:
    expose_as: "Code Quality Report"
    paths: [gl-code-quality-report.html]

metrics:
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
